using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using Netsuite.Enum;

namespace Netsuite.Dto
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
//

/// <remarks/>
[GeneratedCode("wsdl", "4.8.3928.0")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(Namespace="urn:core_2021_1.platform.webservices.netsuite.com")]
public partial class GetIntegrationGovernanceInfoResult {

    private Status statusField;

    private long integrationConcurrencyLimitField;

    private bool integrationConcurrencyLimitFieldSpecified;

    private GetIntegrationGovernanceInfoLimitType limitTypeField;

    private bool limitTypeFieldSpecified;

    /// <remarks/>
    public Status status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }

    /// <remarks/>
    public long integrationConcurrencyLimit {
        get {
            return this.integrationConcurrencyLimitField;
        }
        set {
            this.integrationConcurrencyLimitField = value;
        }
    }

    /// <remarks/>
    [XmlIgnore()]
    public bool integrationConcurrencyLimitSpecified {
        get {
            return this.integrationConcurrencyLimitFieldSpecified;
        }
        set {
            this.integrationConcurrencyLimitFieldSpecified = value;
        }
    }

    /// <remarks/>
    public GetIntegrationGovernanceInfoLimitType limitType {
        get {
            return this.limitTypeField;
        }
        set {
            this.limitTypeField = value;
        }
    }

    /// <remarks/>
    [XmlIgnore()]
    public bool limitTypeSpecified {
        get {
            return this.limitTypeFieldSpecified;
        }
        set {
            this.limitTypeFieldSpecified = value;
        }
    }
}
}
