using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using Netsuite.Enum;

namespace Netsuite.Dto
{
    /// <remarks/>
    [GeneratedCode("wsdl", "4.8.3928.0")]
    [SerializableAttribute()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "urn:sales_2021_1.transactions.webservices.netsuite.com")]
    public partial class SalesOrder : Record
    {
        #region private autogenerated fields

        private DateTime _createdDateField;

        private RecordRef _customFormField;

        private RecordRef _jobField;

        private RecordRef _currencyField;

        private RecordRef _drAccountField;

        private RecordRef _fxAccountField;

        private DateTime _tranDateField;

        private string _tranIdField;

        private RecordRef _entityTaxRegNumField;

        private string _sourceField;

        private RecordRef _createdFromField;

        private SalesOrderOrderStatus _orderStatusField;

        private RecordRef _opportunityField;

        private RecordRef _salesRepField;

        private string _contribPctField;

        private RecordRef _partnerField;

        private RecordRef _salesGroupField;

        private bool _syncSalesTeamsField;

        private RecordRef _leadSourceField;

        private DateTime _startDateField;

        private DateTime _endDateField;

        private string _otherRefNumField;

        private string _memoField;

        private DateTime _salesEffectiveDateField;

        private bool _excludeCommissionField;

        private decimal _totalCostEstimateField;

        private decimal _estGrossProfitField;

        private decimal _estGrossProfitPercentField;

        private decimal _exchangeRateField;

        private RecordRef _promoCodeField;

        private string _currencyNameField;

        private RecordRef _discountItemField;

        private string _discountRateField;

        private bool _isTaxableField;

        private RecordRef _taxItemField;

        private decimal _taxRateField;

        private bool _toBePrintedField;

        private bool _toBeEmailedField;

        private string _emailField;

        private bool _toBeFaxedField;

        private string _faxField;

        private RecordRef _messageSelField;

        private string _messageField;

        private RecordRef _paymentOptionField;

        private string _inputAuthCodeField;

        private string _inputReferenceCodeField;

        private string _checkNumberField;

        private string _paymentCardCscField;

        private RecordRef _paymentProcessingProfileField;

        private string _outputAuthCodeField;

        private string _outputReferenceCodeField;

        private string _dynamicDescriptorField;

        private string _billingAddressField;

        private RecordRef _billAddressListField;

        private string _shippingAddressField;

        private bool _shipIsResidentialField;

        private RecordRef _shipAddressListField;

        private string _fobField;

        private DateTime _actualShipDateField;

        private RecordRef _shipMethodField;

        private decimal _shippingCostField;

        private decimal _shippingTax1RateField;

        private bool _isMultiShipToField;

        private string _shippingTax2RateField;

        private RecordRef _shippingTaxCodeField;

        private RecordRef _handlingTaxCodeField;

        private decimal _handlingTax1RateField;

        private string _handlingTax2RateField;

        private decimal _handlingCostField;

        private string _trackingNumbersField;

        private string _linkedTrackingNumbersField;

        private bool _shipCompleteField;

        private RecordRef _paymentMethodField;

        private string _shopperIpAddressField;

        private bool _saveOnAuthDeclineField;

        private bool _canHaveStackableField;

        private RecordRef _creditCardField;

        private decimal _recognizedRevenueField;

        private decimal _deferredRevenueField;

        private bool _revRecOnRevCommitmentField;

        private string _ccNumberField;

        private DateTime _ccExpireDateField;

        private string _ccNameField;

        private string _ccStreetField;

        private string _ccZipCodeField;

        private string _payPalStatusField;

        private RecordRef _creditCardProcessorField;

        private string _payPalTranIdField;

        private bool _ccApprovedField;

        private bool _getAuthField;

        private string _authCodeField;

        private bool _isRecurringPaymentField;

        private decimal _altSalesTotalField;

        private bool _ignoreAvsField;

        private DateTime _paymentEventDateField;

        private string _paymentEventUpdatedByField;

        private decimal _subTotalField;

        private decimal _discountTotalField;

        private decimal _taxTotalField;

        private decimal _altShippingCostField;

        private decimal _altHandlingCostField;

        private decimal _totalField;

        private RecordRef _revRecScheduleField;

        private DateTime _revRecStartDateField;

        private DateTime _revRecEndDateField;

        private string _paypalAuthIdField;

        private decimal _balanceField;
        
        private bool _paypalProcessField;

        private RecordRef _billingScheduleField;

        private string _ccSecurityCodeField;

        private string _threeDStatusCodeField;

        private RecordRef _classField;

        private RecordRef _departmentField;

        private RecordRef _subsidiaryField;

        private RecordRef _intercoTransactionField;

        private string _debitCardIssueNoField;

        private DateTime _lastModifiedDateField;

        private RecordRef _nexusField;

        private RecordRef _subsidiaryTaxRegNumField;

        private bool _taxRegOverrideField;

        private DateTime _taxPointDateField;

        private bool _taxDetailsOverrideField;

        private RecordRef _locationField;

        private string _pnRefNumField;

        private string _statusField;

        private decimal _tax2TotalField;

        private RecordRef _termsField;

        private DateTime _validFromField;

        private string _vatRegNumField;

        private decimal _giftCertAppliedField;

        private decimal _oneTimeField;

        private decimal _recurWeeklyField;

        private decimal _recurMonthlyField;

        private decimal _recurQuarterlyField;

        private decimal _recurAnnuallyField;

        private bool _tranIsVsoeBundleField;

        private bool _vsoeAutoCalcField;

        private bool _syncPartnerTeamsField;

        private SalesOrderSalesTeamList _salesTeamListField;

        private SalesOrderPartnersList _partnersListField;

        private GiftCertRedemptionList _giftCertRedemptionListField;

        private PromotionsList _promotionsListField;

        private SalesOrderItem[] _itemListField;

        private SalesOrderShipGroupList _shipGroupListField;

        private AccountingBookDetailList _accountingBookDetailListField;

        private TaxDetailsList _taxDetailsListField;

        private CustomFieldRef[] _customFieldListField;

        private string _internalIdField;

        private string _externalIdField;

        #endregion

        public bool Voided { get; set; }
        public decimal OverallBalance { get; set; }
        public string Version { get; set; }
        public string ShipAddress { get; set; }
        public string BillAddress { get; set; }
        public string PrimaryCurrency { get; set; }
        public decimal ItemTotal { get; set; }
        public string Edition { get; set; }
        public string BillingAddress_Key { get; set; }
        public string ShippingAddress_Key { get; set; }
        public string ShippingAddress_Text { get; set; }
        public string BillingAddress_Text { get; set; }
        public string ShippingAddressType { get; set; }
        public bool BillIsResidential { get; set; }
        public decimal OrigTotal { get; set; }
        public string ForeignTotal { get; set; }
        public DateTime NextBillDate { get; set; }
        public string Entity { get; set; }
        public DateTime? ShipDate { get; set; }

        #region public auto genereated

        /// <remarks/>
        public DateTime CreatedDate
        {
            get => _createdDateField;
            set => _createdDateField = value;
        }

        /// <remarks/>
        public RecordRef CustomForm
        {
            get => _customFormField;
            set => _customFormField = value;
        }

        /// <remarks/>
        public RecordRef Job
        {
            get => _jobField;
            set => _jobField = value;
        }

        /// <remarks/>
        public RecordRef Currency
        {
            get => _currencyField;
            set => _currencyField = value;
        }

        /// <remarks/>
        public RecordRef DrAccount
        {
            get => _drAccountField;
            set => _drAccountField = value;
        }

        /// <remarks/>
        public RecordRef FxAccount
        {
            get => _fxAccountField;
            set => _fxAccountField = value;
        }

        /// <remarks/>
        public DateTime TranDate
        {
            get => _tranDateField;
            set => _tranDateField = value;
        }

        /// <remarks/>
        public string TranId
        {
            get => _tranIdField;
            set => _tranIdField = value;
        }

        /// <remarks/>
        public RecordRef EntityTaxRegNum
        {
            get => _entityTaxRegNumField;
            set => _entityTaxRegNumField = value;
        }

        /// <remarks/>
        public string Source
        {
            get => _sourceField;
            set => _sourceField = value;
        }

        /// <remarks/>
        public RecordRef CreatedFrom
        {
            get => _createdFromField;
            set => _createdFromField = value;
        }

        /// <remarks/>
        public SalesOrderOrderStatus OrderStatus
        {
            get => _orderStatusField;
            set => _orderStatusField = value;
        }

        /// <remarks/>
        public RecordRef Opportunity
        {
            get => _opportunityField;
            set => _opportunityField = value;
        }

        /// <remarks/>
        public RecordRef SalesRep
        {
            get => _salesRepField;
            set => _salesRepField = value;
        }

        /// <remarks/>
        public string ContribPct
        {
            get => _contribPctField;
            set => _contribPctField = value;
        }

        /// <remarks/>
        public RecordRef Partner
        {
            get => _partnerField;
            set => _partnerField = value;
        }

        /// <remarks/>
        public RecordRef SalesGroup
        {
            get => _salesGroupField;
            set => _salesGroupField = value;
        }

        /// <remarks/>
        public bool SyncSalesTeams
        {
            get => _syncSalesTeamsField;
            set => _syncSalesTeamsField = value;
        }
        /// <remarks/>
        public RecordRef LeadSource
        {
            get => _leadSourceField;
            set => _leadSourceField = value;
        }

        /// <remarks/>
        public DateTime StartDate
        {
            get => _startDateField;
            set => _startDateField = value;
        }

        /// <remarks/>
        public DateTime EndDate
        {
            get => _endDateField;
            set => _endDateField = value;
        }

        /// <remarks/>
        public string OtherRefNum
        {
            get => _otherRefNumField;
            set => _otherRefNumField = value;
        }

        /// <remarks/>
        public string Memo
        {
            get => _memoField;
            set => _memoField = value;
        }

        /// <remarks/>
        public DateTime SalesEffectiveDate
        {
            get => _salesEffectiveDateField;
            set => _salesEffectiveDateField = value;
        }

        /// <remarks/>
        public bool ExcludeCommission
        {
            get => _excludeCommissionField;
            set => _excludeCommissionField = value;
        }

        /// <remarks/>
        public decimal TotalCostEstimate
        {
            get => _totalCostEstimateField;
            set => _totalCostEstimateField = value;
        }

        /// <remarks/>
        public decimal EstGrossProfit
        {
            get => _estGrossProfitField;
            set => _estGrossProfitField = value;
        }

        /// <remarks/>
        public decimal EstGrossProfitPercent
        {
            get => _estGrossProfitPercentField;
            set => _estGrossProfitPercentField = value;
        }

        /// <remarks/>
        public decimal ExchangeRate
        {
            get => _exchangeRateField;
            set => _exchangeRateField = value;
        }

        /// <remarks/>
        public RecordRef PromoCode
        {
            get => _promoCodeField;
            set => _promoCodeField = value;
        }

        /// <remarks/>
        public string CurrencyName
        {
            get => _currencyNameField;
            set => _currencyNameField = value;
        }

        /// <remarks/>
        public RecordRef DiscountItem
        {
            get => _discountItemField;
            set => _discountItemField = value;
        }

        /// <remarks/>
        public string DiscountRate
        {
            get => _discountRateField;
            set => _discountRateField = value;
        }

        /// <remarks/>
        public bool IsTaxable
        {
            get => _isTaxableField;
            set => _isTaxableField = value;
        }

        /// <remarks/>
        public RecordRef TaxItem
        {
            get => _taxItemField;
            set => _taxItemField = value;
        }

        /// <remarks/>
        public decimal TaxRate
        {
            get => _taxRateField;
            set => _taxRateField = value;
        }

        /// <remarks/>
        public bool ToBePrinted
        {
            get => _toBePrintedField;
            set => _toBePrintedField = value;
        }

        /// <remarks/>
        public bool ToBeEmailed
        {
            get => _toBeEmailedField;
            set => _toBeEmailedField = value;
        }

        /// <remarks/>
        public string Email
        {
            get => _emailField;
            set => _emailField = value;
        }

        /// <remarks/>
        public bool ToBeFaxed
        {
            get => _toBeFaxedField;
            set => _toBeFaxedField = value;
        }

        /// <remarks/>
        public string Fax
        {
            get => _faxField;
            set => _faxField = value;
        }

        /// <remarks/>
        public RecordRef MessageSel
        {
            get => _messageSelField;
            set => _messageSelField = value;
        }

        /// <remarks/>
        public string Message
        {
            get => _messageField;
            set => _messageField = value;
        }

        /// <remarks/>
        public RecordRef PaymentOption
        {
            get => _paymentOptionField;
            set => _paymentOptionField = value;
        }

        /// <remarks/>
        public string InputAuthCode
        {
            get => _inputAuthCodeField;
            set => _inputAuthCodeField = value;
        }

        /// <remarks/>
        public string InputReferenceCode
        {
            get => _inputReferenceCodeField;
            set => _inputReferenceCodeField = value;
        }

        /// <remarks/>
        public string CheckNumber
        {
            get => _checkNumberField;
            set => _checkNumberField = value;
        }

        /// <remarks/>
        public string PaymentCardCsc
        {
            get => _paymentCardCscField;
            set => _paymentCardCscField = value;
        }

        /// <remarks/>
        public RecordRef PaymentProcessingProfile
        {
            get => _paymentProcessingProfileField;
            set => _paymentProcessingProfileField = value;
        }

        /// <remarks/>
        public string OutputAuthCode
        {
            get => _outputAuthCodeField;
            set => _outputAuthCodeField = value;
        }

        /// <remarks/>
        public string OutputReferenceCode
        {
            get => _outputReferenceCodeField;
            set => _outputReferenceCodeField = value;
        }

        /// <remarks/>
        public string DynamicDescriptor
        {
            get => _dynamicDescriptorField;
            set => _dynamicDescriptorField = value;
        }

        /// <remarks/>
        public string BillingAddress
        {
            get => _billingAddressField;
            set => _billingAddressField = value;
        }

        /// <remarks/>
        public RecordRef BillAddressList
        {
            get => _billAddressListField;
            set => _billAddressListField = value;
        }

        /// <remarks/>
        public string ShippingAddress
        {
            get => _shippingAddressField;
            set => _shippingAddressField = value;
        }

        /// <remarks/>
        public bool ShipIsResidential
        {
            get => _shipIsResidentialField;
            set => _shipIsResidentialField = value;
        }

        /// <remarks/>
        public RecordRef ShipAddressList
        {
            get => _shipAddressListField;
            set => _shipAddressListField = value;
        }

        /// <remarks/>
        public string Fob
        {
            get => _fobField;
            set => _fobField = value;
        }

        /// <remarks/>
        public DateTime ActualShipDate
        {
            get => _actualShipDateField;
            set => _actualShipDateField = value;
        }
        /// <remarks/>
        public RecordRef ShipMethod
        {
            get => _shipMethodField;
            set => _shipMethodField = value;
        }

        /// <remarks/>
        public decimal ShippingCost
        {
            get => _shippingCostField;
            set => _shippingCostField = value;
        }

        /// <remarks/>
        public decimal ShippingTax1Rate
        {
            get => _shippingTax1RateField;
            set => _shippingTax1RateField = value;
        }

        /// <remarks/>
        public bool IsMultiShipTo
        {
            get => _isMultiShipToField;
            set => _isMultiShipToField = value;
        }

        /// <remarks/>
        public string ShippingTax2Rate
        {
            get => _shippingTax2RateField;
            set => _shippingTax2RateField = value;
        }

        /// <remarks/>
        public RecordRef ShippingTaxCode
        {
            get => _shippingTaxCodeField;
            set => _shippingTaxCodeField = value;
        }

        /// <remarks/>
        public RecordRef HandlingTaxCode
        {
            get => _handlingTaxCodeField;
            set => _handlingTaxCodeField = value;
        }

        /// <remarks/>
        public decimal HandlingTax1Rate
        {
            get => _handlingTax1RateField;
            set => _handlingTax1RateField = value;
        }

        /// <remarks/>
        public string HandlingTax2Rate
        {
            get => _handlingTax2RateField;
            set => _handlingTax2RateField = value;
        }

        /// <remarks/>
        public decimal HandlingCost
        {
            get => _handlingCostField;
            set => _handlingCostField = value;
        }

        /// <remarks/>
        public string TrackingNumbers
        {
            get => _trackingNumbersField;
            set => _trackingNumbersField = value;
        }

        /// <remarks/>
        public string LinkedTrackingNumbers
        {
            get => _linkedTrackingNumbersField;
            set => _linkedTrackingNumbersField = value;
        }

        /// <remarks/>
        public bool ShipComplete
        {
            get => _shipCompleteField;
            set => _shipCompleteField = value;
        }

        /// <remarks/>
        public RecordRef PaymentMethod
        {
            get => _paymentMethodField;
            set => _paymentMethodField = value;
        }

        /// <remarks/>
        public string ShopperIpAddress
        {
            get => _shopperIpAddressField;
            set => _shopperIpAddressField = value;
        }

        /// <remarks/>
        public bool SaveOnAuthDecline
        {
            get => _saveOnAuthDeclineField;
            set => _saveOnAuthDeclineField = value;
        }

        /// <remarks/>
        public bool CanHaveStackable
        {
            get => _canHaveStackableField;
            set => _canHaveStackableField = value;
        }

        /// <remarks/>
        public RecordRef CreditCard
        {
            get => _creditCardField;
            set => _creditCardField = value;
        }

        /// <remarks/>
        public decimal RecognizedRevenue
        {
            get => _recognizedRevenueField;
            set => _recognizedRevenueField = value;
        }

        /// <remarks/>
        public decimal DeferredRevenue
        {
            get => _deferredRevenueField;
            set => _deferredRevenueField = value;
        }

        /// <remarks/>
        public bool RevRecOnRevCommitment
        {
            get => _revRecOnRevCommitmentField;
            set => _revRecOnRevCommitmentField = value;
        }

        /// <remarks/>
        public string CcNumber
        {
            get => _ccNumberField;
            set => _ccNumberField = value;
        }

        /// <remarks/>
        public DateTime CcExpireDate
        {
            get => _ccExpireDateField;
            set => _ccExpireDateField = value;
        }

        /// <remarks/>
        public string CcName
        {
            get => _ccNameField;
            set => _ccNameField = value;
        }

        /// <remarks/>
        public string CcStreet
        {
            get => _ccStreetField;
            set => _ccStreetField = value;
        }

        /// <remarks/>
        public string CcZipCode
        {
            get => _ccZipCodeField;
            set => _ccZipCodeField = value;
        }

        /// <remarks/>
        public string PayPalStatus
        {
            get => _payPalStatusField;
            set => _payPalStatusField = value;
        }

        /// <remarks/>
        public RecordRef CreditCardProcessor
        {
            get => _creditCardProcessorField;
            set => _creditCardProcessorField = value;
        }

        /// <remarks/>
        public string PayPalTranId
        {
            get => _payPalTranIdField;
            set => _payPalTranIdField = value;
        }

        /// <remarks/>
        public bool CcApproved
        {
            get => _ccApprovedField;
            set => _ccApprovedField = value;
        }

        /// <remarks/>
        public bool GetAuth
        {
            get => _getAuthField;
            set => _getAuthField = value;
        }

        /// <remarks/>
        public string AuthCode
        {
            get => _authCodeField;
            set => _authCodeField = value;
        }

        /// <remarks/>
        public bool IsRecurringPayment
        {
            get => _isRecurringPaymentField;
            set => _isRecurringPaymentField = value;
        }

        /// <remarks/>
        public decimal AltSalesTotal
        {
            get => _altSalesTotalField;
            set => _altSalesTotalField = value;
        }

        /// <remarks/>
        public bool IgnoreAvs
        {
            get => _ignoreAvsField;
            set => _ignoreAvsField = value;
        }

       /// <remarks/>
        public DateTime PaymentEventDate
        {
            get => _paymentEventDateField;
            set => _paymentEventDateField = value;
        }

        /// <remarks/>
        public string PaymentEventUpdatedBy
        {
            get => _paymentEventUpdatedByField;
            set => _paymentEventUpdatedByField = value;
        }

        /// <remarks/>
        public decimal SubTotal
        {
            get => _subTotalField;
            set => _subTotalField = value;
        }

        /// <remarks/>
        public decimal DiscountTotal
        {
            get => _discountTotalField;
            set => _discountTotalField = value;
        }

        /// <remarks/>
        public decimal TaxTotal
        {
            get => _taxTotalField;
            set => _taxTotalField = value;
        }

        /// <remarks/>
        public decimal AltShippingCost
        {
            get => _altShippingCostField;
            set => _altShippingCostField = value;
        }

        /// <remarks/>
        public decimal AltHandlingCost
        {
            get => _altHandlingCostField;
            set => _altHandlingCostField = value;
        }

        /// <remarks/>
        public decimal Total
        {
            get => _totalField;
            set => _totalField = value;
        }

        /// <remarks/>
        public RecordRef RevRecSchedule
        {
            get => _revRecScheduleField;
            set => _revRecScheduleField = value;
        }

        /// <remarks/>
        public DateTime RevRecStartDate
        {
            get => _revRecStartDateField;
            set => _revRecStartDateField = value;
        }

        /// <remarks/>
        public DateTime RevRecEndDate
        {
            get => _revRecEndDateField;
            set => _revRecEndDateField = value;
        }

        /// <remarks/>
        public string PaypalAuthId
        {
            get => _paypalAuthIdField;
            set => _paypalAuthIdField = value;
        }

        /// <remarks/>
        public decimal Balance
        {
            get => _balanceField;
            set => _balanceField = value;
        }

        /// <remarks/>
        public bool PaypalProcess
        {
            get => _paypalProcessField;
            set => _paypalProcessField = value;
        }

        /// <remarks/>
        public RecordRef BillingSchedule
        {
            get => _billingScheduleField;
            set => _billingScheduleField = value;
        }

        /// <remarks/>
        public string CcSecurityCode
        {
            get => _ccSecurityCodeField;
            set => _ccSecurityCodeField = value;
        }

        /// <remarks/>
        public string ThreeDStatusCode
        {
            get => _threeDStatusCodeField;
            set => _threeDStatusCodeField = value;
        }

        /// <remarks/>
        public RecordRef Class
        {
            get => _classField;
            set => _classField = value;
        }

        /// <remarks/>
        public RecordRef Department
        {
            get => _departmentField;
            set => _departmentField = value;
        }

        /// <remarks/>
        public RecordRef Subsidiary
        {
            get => _subsidiaryField;
            set => _subsidiaryField = value;
        }

        /// <remarks/>
        public RecordRef IntercoTransaction
        {
            get => _intercoTransactionField;
            set => _intercoTransactionField = value;
        }

        /// <remarks/>
        public string DebitCardIssueNo
        {
            get => _debitCardIssueNoField;
            set => _debitCardIssueNoField = value;
        }

        /// <remarks/>
        public DateTime LastModifiedDate
        {
            get => _lastModifiedDateField;
            set => _lastModifiedDateField = value;
        }

        /// <remarks/>
        public RecordRef Nexus
        {
            get => _nexusField;
            set => _nexusField = value;
        }

        /// <remarks/>
        public RecordRef SubsidiaryTaxRegNum
        {
            get => _subsidiaryTaxRegNumField;
            set => _subsidiaryTaxRegNumField = value;
        }

        /// <remarks/>
        public bool TaxRegOverride
        {
            get => _taxRegOverrideField;
            set => _taxRegOverrideField = value;
        }

        /// <remarks/>
        public DateTime TaxPointDate
        {
            get => _taxPointDateField;
            set => _taxPointDateField = value;
        }

        /// <remarks/>
        public bool TaxDetailsOverride
        {
            get => _taxDetailsOverrideField;
            set => _taxDetailsOverrideField = value;
        }

        /// <remarks/>
        public RecordRef Location
        {
            get => _locationField;
            set => _locationField = value;
        }

        /// <remarks/>
        public string PnRefNum
        {
            get => _pnRefNumField;
            set => _pnRefNumField = value;
        }

        /// <remarks/>
        public string Status
        {
            get => _statusField;
            set => _statusField = value;
        }

        /// <remarks/>
        public decimal Tax2Total
        {
            get => _tax2TotalField;
            set => _tax2TotalField = value;
        }

        /// <remarks/>
        public RecordRef Terms
        {
            get => _termsField;
            set => _termsField = value;
        }

        /// <remarks/>
        public DateTime ValidFrom
        {
            get => _validFromField;
            set => _validFromField = value;
        }
        /// <remarks/>
        public string VatRegNum
        {
            get => _vatRegNumField;
            set => _vatRegNumField = value;
        }

        /// <remarks/>
        public decimal GiftCertApplied
        {
            get => _giftCertAppliedField;
            set => _giftCertAppliedField = value;
        }

        /// <remarks/>
        public decimal OneTime
        {
            get => _oneTimeField;
            set => _oneTimeField = value;
        }

        /// <remarks/>
        public decimal RecurWeekly
        {
            get => _recurWeeklyField;
            set => _recurWeeklyField = value;
        }

        /// <remarks/>
        public decimal RecurMonthly
        {
            get => _recurMonthlyField;
            set => _recurMonthlyField = value;
        }

        /// <remarks/>
        public decimal RecurQuarterly
        {
            get => _recurQuarterlyField;
            set => _recurQuarterlyField = value;
        }

        /// <remarks/>
        public decimal RecurAnnually
        {
            get => _recurAnnuallyField;
            set => _recurAnnuallyField = value;
        }

        /// <remarks/>
        public bool TranIsVsoeBundle
        {
            get => _tranIsVsoeBundleField;
            set => _tranIsVsoeBundleField = value;
        }

        /// <remarks/>
        public bool VsoeAutoCalc
        {
            get => _vsoeAutoCalcField;
            set => _vsoeAutoCalcField = value;
        }

        /// <remarks/>
        public bool SyncPartnerTeams
        {
            get => _syncPartnerTeamsField;
            set => _syncPartnerTeamsField = value;
        }

        /// <remarks/>
        public SalesOrderSalesTeamList SalesTeamList
        {
            get => _salesTeamListField;
            set => _salesTeamListField = value;
        }

        /// <remarks/>
        public SalesOrderPartnersList PartnersList
        {
            get => _partnersListField;
            set => _partnersListField = value;
        }

        /// <remarks/>
        public GiftCertRedemptionList GiftCertRedemptionList
        {
            get => _giftCertRedemptionListField;
            set => _giftCertRedemptionListField = value;
        }

        /// <remarks/>
        public PromotionsList PromotionsList
        {
            get => _promotionsListField;
            set => _promotionsListField = value;
        }

        /// <remarks/>
        public SalesOrderItem[] Item
        {
            get => _itemListField;
            set => _itemListField = value;
        }

        /// <remarks/>
        public SalesOrderShipGroupList ShipGroupList
        {
            get => _shipGroupListField;
            set => _shipGroupListField = value;
        }

        /// <remarks/>
        public AccountingBookDetailList AccountingBookDetailList
        {
            get => _accountingBookDetailListField;
            set => _accountingBookDetailListField = value;
        }

        /// <remarks/>
        public TaxDetailsList TaxDetailsList
        {
            get => _taxDetailsListField;
            set => _taxDetailsListField = value;
        }

        /// <remarks/>
        [XmlArrayItemAttribute("customField", Namespace = "urn:core_2021_1.platform.webservices.netsuite.com", IsNullable = false)]
        public CustomFieldRef[] CustomFieldList
        {
            get => _customFieldListField;
            set => _customFieldListField = value;
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string InternalId
        {
            get => _internalIdField;
            set => _internalIdField = value;
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string ExternalId
        {
            get => _externalIdField;
            set => _externalIdField = value;
        }

        #endregion
    }
}
