using System;
using Netsuite.Enum;

namespace Netsuite.Dto
{
    public partial class SalesOrder : Record
    {
        public bool Voided { get; set; }
        public decimal OverallBalance { get; set; }
        public string Version { get; set; }
        public string ShipAddress { get; set; }
        public string BillAddress { get; set; }
        public string PrimaryCurrency { get; set; }
        public decimal ItemTotal { get; set; }
        public string Edition { get; set; }
        public string BillingAddress_Key { get; set; }
        public string ShippingAddress_Key { get; set; }
        public string ShippingAddress_Text { get; set; }
        public string BillingAddress_Text { get; set; }
        public string ShippingAddressType { get; set; }
        public bool BillIsResidential { get; set; }
        public decimal OrigTotal { get; set; }
        public string ForeignTotal { get; set; }
        public DateTime NextBillDate { get; set; }
        public string Entity { get; set; }
        public DateTime? ShipDate { get; set; }
        public string CustBody_DN_SO_CustomField1 { get; set; }
        public string CustBody_DN_SO_CustomField2 { get; set; }
        public string CustBody_DN_SO_CustomField3 { get; set; }
        public string CustBody_DN_SO_CustomField4 { get; set; }
        public string CustBody_DN_SO_CustomField5 { get; set; }
        public string CustBody_DN_SO_CustomField6 { get; set; }
        public string CustBody_DN_SO_CustomField7 { get; set; }
        public string CustBody_DN_SO_CustomField8 { get; set; }
        public string CustBody_DN_SO_CustomField9 { get; set; }
        public string CustBody_DN_SO_CustomField10 { get; set; }

        public DateTime CreatedDate { get; set; }
        public RecordRef CustomForm { get; set; }
        public RecordRef Job { get; set; }
        public RecordRef Currency { get; set; }
        public RecordRef DrAccount { get; set; }
        public RecordRef FxAccount { get; set; }
        public DateTime TranDate { get; set; }
        public string TranId { get; set; }
        public RecordRef EntityTaxRegNum { get; set; }
        public string Source { get; set; }
        public RecordRef CreatedFrom { get; set; }
        public SalesOrderOrderStatus OrderStatus { get; set; }
        public RecordRef Opportunity { get; set; }
        public RecordRef SalesRep { get; set; }
        public string ContribPct { get; set; }
        public RecordRef Partner { get; set; }
        public RecordRef SalesGroup { get; set; }
        public bool SyncSalesTeams { get; set; }
        public RecordRef LeadSource { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string OtherRefNum { get; set; }
        public string Memo { get; set; }
        public DateTime? SalesEffectiveDate { get; set; }
        public bool ExcludeCommission { get; set; }
        public decimal TotalCostEstimate { get; set; }
        public decimal EstGrossProfit { get; set; }
        public decimal EstGrossProfitPercent { get; set; }
        public decimal ExchangeRate { get; set; }
        public RecordRef PromoCode { get; set; }
        public string CurrencyName { get; set; }
        public RecordRef DiscountItem { get; set; }
        public string DiscountRate { get; set; }
        public bool IsTaxable { get; set; }
        public RecordRef TaxItem { get; set; }
        public decimal TaxRate { get; set; }
        public bool ToBePrinted { get; set; }
        public bool ToBeEmailed { get; set; }
        public string Email { get; set; }
        public bool ToBeFaxed { get; set; }
        public string Fax { get; set; }
        public RecordRef MessageSel { get; set; }
        public string Message { get; set; }
        public RecordRef PaymentOption { get; set; }
        public string InputAuthCode { get; set; }
        public string InputReferenceCode { get; set; }
        public string CheckNumber { get; set; }
        public string PaymentCardCsc { get; set; }
        public RecordRef PaymentProcessingProfile { get; set; }
        public string OutputAuthCode { get; set; }
        public string OutputReferenceCode { get; set; }
        public string DynamicDescriptor { get; set; }
        public string BillingAddress { get; set; }
        public RecordRef BillAddressList { get; set; }
        public string ShippingAddress { get; set; }
        public bool ShipIsResidential { get; set; }
        public RecordRef ShipAddressList { get; set; }
        public string Fob { get; set; }
        public DateTime ActualShipDate { get; set; }
        public RecordRef ShipMethod { get; set; }
        public decimal ShippingCost { get; set; }
        public decimal ShippingTax1Rate { get; set; }
        public bool IsMultiShipTo { get; set; }
        public string ShippingTax2Rate { get; set; }
        public decimal HandlingTax1Rate { get; set; }
        public string HandlingTax2Rate { get; set; }
        public decimal HandlingCost { get; set; }
        public string TrackingNumbers { get; set; }
        public string LinkedTrackingNumbers { get; set; }
        public bool ShipComplete { get; set; }
        public string ShopperIpAddress { get; set; }
        public bool SaveOnAuthDecline { get; set; }
        public bool CanHaveStackable { get; set; }
        public decimal RecognizedRevenue { get; set; }
        public decimal DeferredRevenue { get; set; }
        public bool RevRecOnRevCommitment { get; set; }
        public bool GetAuth { get; set; }
        public string AuthCode { get; set; }
        public bool IsRecurringPayment { get; set; }
        public decimal AltSalesTotal { get; set; }
        public bool IgnoreAvs { get; set; }
        public DateTime? PaymentEventDate { get; set; }
        public string PaymentEventUpdatedBy { get; set; }
        public decimal SubTotal { get; set; }
        public decimal DiscountTotal { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal AltShippingCost { get; set; }
        public decimal AltHandlingCost { get; set; }
        public decimal Total { get; set; }
        public DateTime? RevRecStartDate { get; set; }
        public DateTime? RevRecEndDate { get; set; }
        public string PaypalAuthId { get; set; }
        public decimal Balance { get; set; }
        public bool PaypalProcess { get; set; }
        public string CcSecurityCode { get; set; }
        public string ThreeDStatusCode { get; set; }
        public RecordRef Class { get; set; }
        public RecordRef Department { get; set; }
        public RecordRef Subsidiary { get; set; }
        public RecordRef IntercoTransaction { get; set; }
        public string DebitCardIssueNo { get; set; }
        public DateTime LastModifiedDate { get; set; }
        public RecordRef Location { get; set; }
        public string PnRefNum { get; set; }
        public string Status { get; set; }
        public decimal Tax2Total { get; set; }
        public DateTime? ValidFrom { get; set; }
        public string VatRegNum { get; set; }
        public decimal GiftCertApplied { get; set; }
        public decimal OneTime { get; set; }
        public decimal RecurWeekly { get; set; }
        public decimal RecurMonthly { get; set; }
        public decimal RecurQuarterly { get; set; }
        public decimal RecurAnnually { get; set; }
        public bool TranIsVsoeBundle { get; set; }
        public bool VsoeAutoCalc { get; set; }
        public bool SyncPartnerTeams { get; set; }
        public SalesOrderItem[] Item { get; set; }
        public SalesOrderShipGroupList ShipGroupList { get; set; }
    }
}
